This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./Masterthesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Masterthesis.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (366 comparisons).
Generating output file Masterthesis.acr....done (46 lines written, 0 warnings).
Output written in Masterthesis.acr.
Transcript written in Masterthesis.alg.
